(* Letters A to Z capitals *)
letter_upper = 'A' ... 'Z';

(* Letters a to b lowercase *)
letter_lower = 'a' ... 'A';

(* Letters, capital and lowercase *)
letter = letter_lower | letter_upper;

(* The number 0 *)
zero = '0';

(* Numbers from 1 to 9 *)
digit = '1' ... '9';

(* Numbers, including 0 *)
number = zero | digit;


underscore = '_';
equals = '=';
comma = ',';
colon = ':';
left_parenthesis = '(';
right_parenthesis = ')';
left_brace = '{';
right_brace = '}';

(* Identifiers 
 * ===========
 * These are valid given names usually used for names of:
 *   - classes
 *   - variables
 *   - paramters
 * 
 * Example for a variable:
 * ```
 * aBc
 * _abc
 * _123
 * _a1B2c_
 * ```
 *)
identifier = letter | underscore, { letter | number | underscore };

(* Param
 * =====
 * Used when assiging some content to an identifier. 
 *
 * See also optional_parm.
 *
 * Example:
 * ```
 * a:b
 * a : b
 * a: b
 * a :b
 * ```
 *)
param = identifier, colon, identifier;

(* Optional Param
 * ==============
 * Used when assiging some content to an identifier.
 * The right hand side (and by virtue the colon) are both optional.
 *
 * Example:
 * ```
 * a: b
 * a
 * ```
 *)
optional_parm = identifier, [ colon, identifier ];

(* Params
 * ======
 * Used when assiging multiple params.
 * The first is always compulsory.
 *
 * Example:
 * ```
 * a: b
 * a
 * ```
 *)
params = param, [ ( comma, param ) ];

(* Constant
 * ========
 * 
 *)
constant = 'val', optional_parm, equals, expression;

(* Variable
 * ========
 * 
 *)
variable = 'var', optional_parm, equals, expression;

(* Function
 * ========
 * 
 *)
function = 'fun', identifier, left_parenthesis, [ params ], right_parenthesis, colon, identifier, left_brace, statements, right_brace;

(* todo *)
if =;

(* todo *)
expression = ;
statement = ;
statements = { statement };