name: CI

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --release --verbose

      - name: Test
        run: cargo test --all --verbose --no-fail-fast --release
